project:
  type: book
  output-dir: docs

# https://quarto.org/docs/reference/projects/books.html

book:
  title: "Biodiverse Spatial Conditions"
  author: "Shawn W Laffan"
  date: "2026-02-05"
  chapters:
    - index.qmd
    - overview.qmd
    - spatial_conditions.qmd
    - variables.qmd
  output-file: "Biodiverse-Spatial-Conditions"
  downloads: [pdf]
  
format:
  html:
    theme: zephyr
    toc: true
    toc-depth: 3
    toc-expand: true
    number-sections: true
    number-depth: 2
    link-external-newwindow: true
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2

editor: source
